# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blaze', '0006_auto_20170616_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
