# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blaze', '0008_auto_20170617_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
